### ISSUE TITLE
Trying to use the library throws a TypeLoadException

### ISSUE THREAD

**Issue by R2D221** [safakgur/value-string#1]
Trying to use the library throws the following exception:

> Inheritance security rules violated while overriding member: 'Dawn.ValueString.System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.

It's a shame because it sounds like a really useful library, but I can't use it.

**Comment by safakgur** [comment]
Fixed with 7a666cf0da63446c97af06bc0aa80202a174e1f7.
